name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
 #https://github.com/marketplace/actions/git-semantic-version?version=v4.0.3       
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      id  : version
      with:
        major_pattern: "major:"
        minor_oattern: "feat:"
        format: "${major}.${minor}.${path}-prerelease${increment}"
        
    - name: Docker login
      env:
        #DOCKER_USER: ergosanitas
        #DOCKER_PASSWORD: dckr_pat_a2RVvrSEVFgOtCOPc0hT3-WQTv8
        #https://github.com/Nest-MicroService-ms/docker-graphql/settings/secrets/actions
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "Inicial Login "
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "new version $NEW_VERSION!!!"
        echo "Inicial Login"
    
    - name: Build Docker Image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker build -t ergosanitas/docker-test-ms:NEW_VERSION .
        docker build -t ergosanitas/docker-test-ms:latest .
    - name: Push Docker Image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker push ergosanitas/docker-test-ms:NEW_VERSION
        docker push ergosanitas/docker-test-ms:latest
        
